female(grace).
male(frank).
fermale(dede).
male(jay).
female(gloria).
male(javier).
female(barb).
male(merle).
male(phill).
parent(grace,phill).
parent(frank, phill).
female(claire).
parent(dede,claire).
parent(jay,claire).
male(mitchel).
parent(dede,mitchel).
parent(jay,mitchel).
male(joe).
parent(jay,joe).
parent(gloria,joe).
male(many).
parent(gloria,many).
parent(javier,many).
male(cameron).
parent(barb,cameron).
parent(merle,cameron).
female(pameron).
parent(barb,pameron).
parent(merle,pameron).
male(bo).
male(dylan).
female(haley).
parent(phill,haley).
parent(claire,haley).
female(alex).
parent(phill,alex).
parent(claire,alex).
male(luke).
parent(phill,luke).
parent(claire,luke).
female(lily).
parent(mitchel,lily).
parent(cameron,lily).
male(rexford).
parent(mitchel,rexford).
parent(cameron,rexford).
male(calhoun).
parent(pameron,calhoun).
parent(bo,calhoun).
male(george).
parent(dylan,george).
parent(haley,george).
female(poppy).
parent(dylan,poppy).
parent(haley,poppy).


marriage(jay,gloria,2008).
marriage(jay,dede,1968).
divorce(jay,dede,2003).